apiVersion: v1
kind: Service
metadata:
  name: {{ include "audio-pipeline-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "audio-pipeline-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-ui
      protocol: TCP
      name: http
  selector:
    {{- include "audio-pipeline-chart.selectorLabels" . | nindent 4 }}